services:
  qr-service:
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file: '.env.local'
    ports:
      - '${PORT}:3000'
    volumes:
    - .:/usr/src/app
    # Run in Debug Mode: npm run start:debug --> Don't forget to start your vscode debugger!
    # Run in dev Mode: npm run start:dev
    command: npm run start:dev
    networks:
      - hackcc-network
  postgres:
    image: postgres
    restart: always
    env_file: '.env.local'
    environment:
      POSTGRES_INITDB_ARGS: "-c max_prepared_transactions=100"
    ports:
      - '5433:5432'
    volumes:
      - ./postgres-data:/data/postgres
    networks:
    - hackcc-network
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    env_file: '.env.local'
    volumes:
      - ./minio/data:/data
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - hackcc-network
networks:
  hackcc-network:
    external: true